### ISSUE TITLE
E & G# & B

### ISSUE THREAD

**Issue by tirnak** [reality3d/3d-piano-player#1]
Hi!
When I'm playing, for example, E & G & B - it's working just fine. 
Or E & Gb & B.

But, when I'm trying to play E & G# & B - at least one of notes doesn't press.

Firefox 36.0 for linux. 
Tried with chromium browser - 3d-piano doesn't work at all.

**Comment by reality3d** [comment]
Hi Tirnak

Thanks for your feedback. It is an old project so I am not planning to fix it, but it would be great if you find a way around it :)
